### PR TITLE
Added OS X Compatibility

### PR DESCRIPTION
**Pull request by manikkalra**
Put in preprocessor directives in check for iOS specific code HysteriaPlayer.m. Also added a small OS X example app.

### CODE REVIEW

**Comment by saiday** [comment]
Thanks @manikkalra, this PR is awesome!

**Comment by manikkalra** [comment]
My pleasure :) Thank you for this awesome audio player! 

I just had one concern I forgot to share. In order to get HysteriaPlayer working correctly on OS X, I had to set ```hysteriaPlayer.skipEmptySoundPlaying = YES;```
Is that expected?

**Comment by saiday** [comment]
@manikkalra 
The reason had to play a point one mp3 at the very first time is to prevent iOS application been sent to background before take audio session. iOS application can't initiate audio session in the background, so that's a workaround. 
I don't think OS X needs this workaround as well.

The root cause of you had to set `skipEmptySoundPlaying = YES` is that `point1sec.mp3` file is not included in your target bundle, I've committed example project.

Thank you.

**Comment by manikkalra** [comment]
Ah got it. Thank you!

**Pull request merged**
