### PR TITLE
Added a method for retrieving the AVQueuePlayer

### PR DESCRIPTION
**Pull request by twgeolo**
We have an OSX app that uses HysteriaPlayer. But, we need to change the volume. So, we are adding a method to expose the internal AVPlayer.

### CODE REVIEW

**Comment by saiday** [comment]
Yeah, it's about time to expose AVPlayer for advanced usage. I had a suggestion about implementation, what if we simply move this property to `HysteriaPlayer.h`?

https://github.com/StreetVoice/HysteriaPlayer/blob/master/HysteriaPlayer/HysteriaPlayer.m#L41

**Comment by manikkalra** [comment]
That would work for us too! Thanks a lot

**Comment by saiday** [comment]
Thanks, merged

**Comment by twgeolo** [comment]
Yup! Thanks :+1:

**Comment by twgeolo** [comment]
Hey, can you create a new release? Our OSX app uses CocoaPods; as a result, our current app still cannot use it. Thank you!!

**Pull request merged**
